---
- include: install_libselinux.yml
- include: disable_selinux.yml
- include: reboot.yml
- include: packages_centos.yml
- include: ntp.yml
- include: hostname.yml
- include: tuning.yml
- include: reboot.yml
